version: '3.0'


services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: register
    restart: always
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    environment:
      - DEBUG=1
      - DB_LOGIN=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=reg
      - DB_HOST=postgres
      - DB_PORT=5432
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_PORT=587
      - EMAIL_USERNAME=7f798118752fe3
      - EMAIL_PASSWORD=8acab4d9422d1b
      - EMAIL_FROM=admin@admin.com
      - REFRESH_TOKEN_EXPIRES_IN=10080
      - ACCESS_TOKEN_EXPIRES_IN=15
      - ALGORITHM=HS256
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    networks:
      - mynetwork

  postgres:
    image: postgres:15.3-alpine
    container_name: register_db
    restart: always
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'reg'


networks:
  mynetwork: