version: '3.0'


services:

  postgres:
    image: postgres:15.3-alpine
    container_name: register_db
    restart: always
    ports:
      - '5455:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'reg'
