"""empty message

Revision ID: 884bee039437
Revises: 
Create Date: 2023-07-09 21:05:51.523679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884bee039437'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('bot_type', sa.Enum('BROADCAST', 'CHAT', 'ANALYTIC', name='bot_type'), nullable=True),
    sa.Column('verify_code', sa.String(), nullable=True),
    sa.Column('in_changes', sa.Boolean(), default=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
